version: "3.8"
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"  
    environment:
      - "DYNAMODB_LOCAL=true"
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
