version: "3.8"
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"  
    environment:
      - DBPATH=/data
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    volumes:
    - ./data:/data